class number{
    getAll() {
        return [
            {name:"Afganistan", kode:"+93"},
            {name:"Afrika Selatan", kode:"+27"},
            {name:"Afrika Tengah", kode:"+236"},
            {name:"Albania", kode:"+355"},
            {name:"Algeria", kode:"+213"},
            {name:"Amerika Serikat", kode:"+1"},
            {name:"Andorra", kode:"+376"},
            {name:"Angola", kode:"+244"},
            {name:"Antigua & Barbuda	1", kode:"+268"},
            {name:"Arab Saudi", kode:"+966"},
            {name:"Argentina", kode:"+54"},
            {name:"Armenia", kode:"+374"},
            {name:"Australia", kode:"+61"},
            {name:"Austria", kode:"+43"},
            {name:"Azerbaijan", kode:"+994"},
            {name:"Bahama	1", kode:"+242"},
            {name:"Bahrain", kode:"+973"},
            {name:"Bangladesh", kode:"+880"},
            {name:"Barbados	1", kode:"+246"},
            {name:"Belanda", kode:"+31"},
            {name:"Belarus", kode:"+375"},
            {name:"Belgia", kode:"+32"},
            {name:"Belize", kode:"+501"},
            {name:"Benin", kode:"+229"},
            {name:"Bhutan", kode:"+975"},
            {name:"Bolivia", kode:"+591"},
            {name:"Bosnia & Herzegovina", kode:"+387"},
            {name:"Botswana", kode:"+267"},
            {name:"Brasil", kode:"+55"},
            {name:"Britania Raya (Inggris)", kode:"+44"},
            {name:"Brunei Darussalam", kode:"+673"},
            {name:"Bulgaria", kode:"+359"},
            {name:"Burkina Faso", kode:"+226"},
            {name:"Burundi", kode:"+257"},
            {name:"Ceko", kode:"+420"},
            {name:"Chad", kode:"+235"},
            {name:"Chili", kode:"+56"},
            {name:"China", kode:"+86"},
            {name:"Denmark", kode:"+45"},
            {name:"Djibouti", kode:"+253"},
            {name:"Domikia	1", kode:"+767"},
            {name:"Ekuador", kode:"+593"},
            {name:"El Salvador", kode:"+503"},
            {name:"Eritrea", kode:"+291"},
            {name:"Estonia", kode:"+372"},
            {name:"Ethiopia", kode:"+251"},
            {name:"Fiji", kode:"+679"},
            {name:"Filipina", kode:"+63"},
            {name:"Finlandia", kode:"+358"},
            {name:"Gabon", kode:"+241"},
            {name:"Gambia", kode:"+220"},
            {name:"Georgia", kode:"+995"},
            {name:"Ghana", kode:"+233"},
            {name:"Grenada	1", kode:"+473"},
            {name:"Guatemala", kode:"+502"},
            {name:"Guinea", kode:"+224"},
            {name:"Guinea Bissau", kode:"+245"},
            {name:"Guinea Khatulistiwa", kode:"+240"},
            {name:"Guyana", kode:"+592"},
            {name:"Haiti", kode:"+509"},
            {name:"Honduras", kode:"+504"},
            {name:"Hongaria", kode:"+36"},
            {name:"Hongkong", kode:"+852"},
            {name:"India", kode:"+91"},
            {name:"Indonesia", kode:"+62"},
            {name:"Irak", kode:"+964"},
            {name:"Iran", kode:"+98"},
            {name:"Irlandia", kode:"+353"},
            {name:"Islandia", kode:"+354"},
            {name:"Israel", kode:"+972"},
            {name:"Italia", kode:"+39"},
            {name:"Jamaika	1", kode:"+876"},
            {name:"Jepang", kode:"+81"},
            {name:"Jerman", kode:"+49"},
            {name:"Jordan", kode:"+962"},
            {name:"Kamboja", kode:"+855"},
            {name:"Kamerun", kode:"+237"},
            {name:"Kanada", kode:"+1"},
            {name:"Kazakhstan", kode:"+7"},
            {name:"Kenya", kode:"+254"},
            {name:"Kirgizstan", kode:"+996"},
            {name:"Kiribati", kode:"+686"},
            {name:"Kolombia", kode:"+57"},
            {name:"Komoro", kode:"+269"},
            {name:"Republik Kongo", kode:"+243"},
            {name:"Korea Selatan", kode:"+82"},
            {name:"Korea Utara", kode:"+850"},
            {name:"Kosta Rika", kode:"+506"},
            {name:"Kroasia", kode:"+385"},
            {name:"Kuba", kode:"+53"},
            {name:"Kuwait", kode:"+965"},
            {name:"Laos", kode:"+856"},
            {name:"Latvia", kode:"+371"},
            {name:"Lebanon", kode:"+961"},
            {name:"Lesotho", kode:"+266"},
            {name:"Liberia", kode:"+231"},
            {name:"Libya", kode:"+218"},
            {name:"Liechtenstein", kode:"+423"},
            {name:"Lituania", kode:"+370"},
            {name:"Luksemburg", kode:"+352"},
            {name:"Madagaskar", kode:"+261"},
            {name:"Makao", kode:"+853"},
            {name:"Makedonia", kode:"+389"},
            {name:"Maladewa", kode:"+960"},
            {name:"Malawi", kode:"+265"},
            {name:"Malaysia", kode:"+60"},
            {name:"Mali", kode:"+223"},
            {name:"Malta", kode:"+356"},
            {name:"Maroko", kode:"+212"},
            {name:"Marshall (Kep.)", kode:"+692"},
            {name:"Mauritania", kode:"+222"},
            {name:"Mauritius", kode:"+230"},
            {name:"Meksiko", kode:"+52"},
            {name:"Mesir", kode:"+20"},
            {name:"Mikronesia (Kep.)", kode:"+691"},
            {name:"Moldova", kode:"+373"},
            {name:"Monako", kode:"+377"},
            {name:"Mongolia", kode:"+976"},
            {name:"Montenegro", kode:"+382"},
            {name:"Mozambik", kode:"+258"},
            {name:"Myanmar", kode:"+95"},
            {name:"Namibia", kode:"+264"},
            {name:"Nauru", kode:"+674"},
            {name:"Nepal", kode:"+977"},
            {name:"Niger", kode:"+227"},
            {name:"Nigeria", kode:"+234"},
            {name:"Nikaragua", kode:"+505"},
            {name:"Norwegia", kode:"+47"},
            {name:"Oman", kode:"+968"},
            {name:"Pakistan", kode:"+92"},
            {name:"Palau", kode:"+680"},
            {name:"Panama", kode:"+507"},
            {name:"Pantai Gading", kode:"+225"},
            {name:"Papua Nugini", kode:"+675"},
            {name:"Paraguay", kode:"+595"},
            {name:"Perancis", kode:"+33"},
            {name:"Peru", kode:"+51"},
            {name:"Polandia", kode:"+48"},
            {name:"Portugal", kode:"+351"},
            {name:"Qatar", kode:"+974"},
            {name:"Rep. Dem. Kongo", kode:"+242"},
            {name:"Republik Dominika	1-809; 1", kode:"+829"},
            {name:"Rumania", kode:"+40"},
            {name:"Rusia", kode:"+7"},
            {name:"Rwanda", kode:"+250"},
            {name:"Saint Kitts and Nevis	1", kode:"+869"},
            {name:"Saint Lucia	1", kode:"+758"},
            {name:"Saint Vincent & the Grenadines	1", kode:"+784"},
            {name:"Samoa", kode:"+685"},
            {name:"San Marino", kode:"+378"},
            {name:"Sao Tome & Principe", kode:"+239"},
            {name:"Selandia Baru", kode:"+64"},
            {name:"Senegal", kode:"+221"},
            {name:"Serbia", kode:"+381"},
            {name:"Seychelles", kode:"+248"},
            {name:"Sierra Leone", kode:"+232"},
            {name:"Singapura", kode:"+65"},
            {name:"Siprus", kode:"+357"},
            {name:"Slovenia", kode:"+386"},
            {name:"Slowakia", kode:"+421"},
            {name:"Solomon (Kep.)", kode:"+677"},
            {name:"Somalia", kode:"+252"},
            {name:"Spanyol", kode:"+34"},
            {name:"Sri Lanka", kode:"+94"},
            {name:"Sudan", kode:"+249"},
            {name:"Sudan Selatan", kode:"+211"},
            {name:"Suriah", kode:"+963"},
            {name:"Suriname", kode:"+597"},
            {name:"Swaziland", kode:"+268"},
            {name:"Swedia", kode:"+46"},
            {name:"Swiss", kode:"+41"},
            {name:"Tajikistan", kode:"+992"},
            {name:"Tanjung Verde", kode:"+238"},
            {name:"Tanzania", kode:"+255"},
            {name:"Taiwan", kode:"+886"},
            {name:"Thailand", kode:"+66"},
            {name:"Timor Leste", kode:"+670"},
            {name:"Togo", kode:"+228"},
            {name:"Tonga", kode:"+676"},
            {name:"Trinidad & Tobago	1", kode:"+868"},
            {name:"Tunisia", kode:"+216"},
            {name:"Turki", kode:"+90"},
            {name:"Turkmenistan", kode:"+993"},
            {name:"Tuvalu", kode:"+688"},
            {name:"Uganda", kode:"+256"},
            {name:"Ukraina", kode:"+380"},
            {name:"Uni Emirat Arab", kode:"+971"},
            {name:"Uruguay", kode:"+598"},
            {name:"Uzbekistan", kode:"+998"},
            {name:"Vanuatu", kode:"+678"},
            {name:"Venezuela", kode:"+58"},
            {name:"Vietnam", kode:"+84"},
            {name:"Yaman", kode:"+967"},
            {name:"Yunani", kode:"+30"},
            {name:"Zambia", kode:"+260"},
            {name:"Zimbabwe", kode:"+263"}
        ];
    }

}

export default number;